### ISSUE TITLE
Error in rapidopgs_multi

### ISSUE THREAD

**Issue by Williamreay** [GRealesM/RapidoPGS#8]
Hi,

I'm running the latest version of RapidoPGS and am trying to implement the multi-variant finemapping via SuSIE. I downloaded the 1000 genomes reference for this purpose via the create_1000G() function.

However, I'm running into an issue which prevents the rapidopgs_multi() function from running. See below for the error message and my input code. Would you be able to provide any insights into this?

ERROR:
Error in susie_suff_stat(XtX = R, Xty = z, n = 2, yty = 1, L = L, scaled_prior_variance = prior_variance,  : 
  unused argument (nref = 405)
Calls: rapidopgs_multi ... withCallingHandlers -> runsusie -> do.call -> <Anonymous>

CODE:

Multi_var_model <- rapidopgs_multi(BC_formatted, trait="cc", reference = "ref-data", ncores=8,
                                   alpha.block = 1, alpha.snp = 1, ancestry = "EUR").

Thanks in advance and best regards,

William Reay

**Comment by GRealesM** [comment]
Dear William,

Thank you for letting us know about the bugs you find while using RápidoPGS. We really appreciate your feedback.

I found the root of your issue. SuSiE has been updated quite a bit recently, so we needed to change some things in our code to keep up. In this case, the argument nref was generated internally and supplied to SuSiE, but it's no longer required -- hence the error.

I've removed this argument from the rapidopgs_multi() function so you may be able to reinstall the package (v2.1.0.9009) and give it a try?

Thanks
Guille

**Comment by Williamreay** [comment]
Hi Guille,

Thank you for your quick response. The script just finished running and it seemed to work fine with your new fix. 

All the best,
William
